[wishosting]
title = "Virtual Private Servers | WISHOSTING"
url = "https://www.wishosting.com/order/main/packages/VPS/?group_id=7"
entrySelector = "div.package"
titleSelector = "div.package-name > h4 , div.price-box > h4"
linkSelector = "entrySelector"
